In [2]:
NAME = "Md. Faisal Iftekhar"
ID = "22299116"
SECTION = "16"

# Part 1: Solving a linear system using inverse matrix - 2 Marks

We have a linear system

\begin{align}
&a_{11} x_1 + a_{12} x_2 +  \cdots  + a_{1n} x_n = b_1\\
&a_{21} x_1 + a_{22} x_2 +  \cdots + a_{2n} x_n = b_2\\
&\cdots\\
&a_{n1} x_1 + a_{n2} x_2 +  \cdots + a_{nn} x_n = b_n\\
\end{align}

It is convenient to express this system in the
matrix form

\begin{align}
Ax = b
\end{align}

where $A$ is an $n \times n$ square matrix with elements $a_{ij}$, and $x$, $b$ are $n \times 1$ vectors.

We have to keep in mind that this system will have a unique solution iff $A$ is non-singular, given by $x = A^{-1}b.$

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import sys

In [13]:
def get_result_by_inverse_matrix(A, b):
  if np.linalg.det(A):
    return np.dot(np.linalg.inv(A),b)
  return "singular matrix"

In [14]:
# Test case for the get_result_by_inverse_matrix(A, b) function.

data_A = np.array([[1, 2, 1], [1, -2, 2], [2, 12, -2]])
data_b = np.array([0,4,4])

test = get_result_by_inverse_matrix(data_A, data_b)
results = [11, -2.5, -6]

np.testing.assert_array_equal(test, results)

# Part 2: Gaussian elimination - 2 Marks

Gaussian elimination uses elementary row operations to transform the system to upper triangular form $Ux = y$.

Elementary row operations include swapping rows and adding multiples of one rowto another.
They won’t change the solution $x$, but will change the matrix $A$ and the right-hand side $b$.

The upper triangular matrix, $𝑈$, is defined as

\begin{bmatrix}
u_{11} & u_{12} & \cdots & u_{1n}\\
0 & u_{22} & \cdots & u_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
0 & \cdots & 0 & u_{nn}\\
\end{bmatrix}


**Algorithm of Gaussian elimination**

Let $A^{(1)}=A$ and $b^{(1)}=b$. Then for each k from 1 to $n-1$, compute a new matrix $A^{(k+1)}$ and right-hand side $b^{(k+1)}$ by the following procedure:


1.   Define the row multipliers

\begin{align}
m_{ij} = \frac{a_{ik}^{(k)}}{a_{kk}^{(k)}}, i=k+1,\cdot \cdot \cdot,n.
\end{align}
2.   Use these to remove the unknown $x_k$ from equations $k + 1$ to $n$, leaving

\begin{align}
a_{ij}^{(k+1)}=a_{ij}^{(k)}-m_{ik}a_{kj}^{(k)}, b_{i}^{(k+1)}=b_{i}^{(k)}-m_{ik}b_{k}^{(k)}, i,j=k+1,\cdot \cdot \cdot, n.
\end{align}

It is helpful to combine these matrices to form an Augmented matrix (matrix $𝑏$ is the fourth column). We will perform this row operations on the Augmented matrix. It takes care of both $𝐴$ and $𝑏$ matrixes at the same time.

After generating the upper triangular matrix, we have to apply **backward substitution method**.
For any $n \times n$ upper triangular system, $Ux = b$, the solution is:

\begin{align}
x_j = \frac{b_j-\sum_{k=j+1}^{n}u_{jk}x_k}{u_{jj}}, j = n, n-1, \cdot\cdot\cdot, 1.
\end{align}

Here we assumed that $det𝑈≠0$.


In [15]:
def get_result_gaussian_elimination(n, A):

  for i in range(n):
    if A[i][i]==0:              #row swap to handle pivoting issues
      for j in range(i+1, n):
        if A[j][i]:
          A[[i,j]]= A[[j,i]]
          break

  x = np.zeros(n)
  for c in range(n):
    for r in range(c+1, n):
      mul = A[r][c]/A[c][c]
      A[r]= A[r]-mul*A[c]

  for i in range(n-1, -1, -1):
    sum = 0
    for j in range(i+1, n):
        sum += A[i][j] * x[j]
    x[i] = (A[i][n] - sum) / A[i][i]

  return x

In [16]:
# Test case for the get_result_gaussian_elimination(n, A) function.

data_n = 3
data_A = np.array([[1, 2, 1, 0], [1, -2, 2, 4], [2, 12, -2, 4]])

test = get_result_gaussian_elimination(data_n, data_A)
results = [11, -2.5, -6]

np.testing.assert_array_equal(test, results)

# Daily Evaluation - 4 Marks

### Task 1


Given the following **2x3 augmented matrix A:**


\begin{bmatrix}
3 & 6 &| & -9\\
1 & 3 &| & 4\\
\end{bmatrix}


Write a function that performs a single step of Gaussian elimination to modify the **second row (row 1)** using the **first row (row 0)**. Specifically, the function should:
1. Calculate the multiplier needed to make the first element of the second row zero.
2. Subtract the necessary multiple of the first row from the second row.


Print the result!


### Task 2


Given the following **3x3** **matrix A**:


A:
\begin{bmatrix}
2 & -1 & 0\\
-1 & 2 & -1\\
0 & -1 & 2\\
\end{bmatrix}


(a) Calculate the **inverse of matrix A** using the matrix inversion method.


(b) Verify your result by showing that **$A.A^{-1} = I$** where I is the Identity Matrix. Print $I$!


$I$:
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
\end{bmatrix}


In [17]:
# Task 1

def single_step_gaussian_elimination(A):
  multiplier = A[1][0] / A[0][0]
  A[1] = A[1] - multiplier * A[0]
  return A

A = np.array([[3, 6, -9], [1, 3, 4]])
result = single_step_gaussian_elimination(A)
print(result)

[[ 3  6 -9]
 [ 0  1  7]]


In [18]:
# Task 2

data_A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
inv_a = np.linalg.pinv(data_A)
x = np.dot(data_A, inv_a)

print(inv_a)

results = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

np.testing.assert_array_equal(x, results)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
